ARC: 9001060878: Disable fanotify tests for ARC
After update to uClibc-ng an LTP test case
testcases/kernel/syscalls/fanotify/fanotify02.c fails to build with an
error:

-------->8--------
In file included from fanotify02.c:40:0:
fanotify02.c: In function 'main':
fanotify02.c:150:43: error: 'O_DIRECTORY' undeclared (first use in this function)
   fd = SAFE_OPEN(cleanup, ".", O_RDONLY | O_DIRECTORY);
                                           ^
../../../../include/safe_macros.h:96:59: note: in definition of macro 'SAFE_OPEN'
  safe_open(__FILE__, __LINE__, (cleanup_fn), (pathname), (oflags), \
                                                           ^
fanotify02.c:150:43: note: each undeclared identifier is reported only once
for each function it appears in
   fd = SAFE_OPEN(cleanup, ".", O_RDONLY | O_DIRECTORY);
                                           ^
../../../../include/safe_macros.h:96:59: note: in definition of macro 'SAFE_OPEN'
  safe_open(__FILE__, __LINE__, (cleanup_fn), (pathname), (oflags), \
                                                           ^
make[4]: *** [fanotify02] Error 1
-------->8--------

This issue is not present with an old uClibc.

Signed-off-by: Anton Kolesov <Anton.Kolesov@synopsys.com>